### ISSUE TITLE
Pass string to cmd version

### ISSUE THREAD

**Issue by flamendless** [ReFreezed/LuaPreprocess#1]
I'm wondering why there's nothing like
`lua preprocess-cmd.lua input.lua output.lua -isdebug`

It would be useful and more appropriate for usage to be able to pass meta information than to make a build system like the one in your löve's example (also check the comment I've made there) 

I have looked at the examples and the lua file itself. I may have missed it.

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ReFreezed** [comment]
Currently you can specify multiple input files to process in one go which is why you can only specify the extension for the output files (with `--outputextension=foo`), but being able to specify the output path in case only one file is to be processed seems like a good idea.

The flag for debug is `--debug`, btw.

**Comment by flamendless** [comment]
I don't want to make another issue since this is minor. But after the processed `.lua2p` to `.lua` file, the `.lua` file contains false indentation at the end.

Example:
```lua
function love.load()
	!if _DEBUG then
		print("woah")
	!end
end
```

this compiles to
```lua
function love.load()
    end //here the indentation is wrong
```

**Comment by flamendless** [comment]
> The flag for debug is `--debug`, btw.

Sorry I've put my words wrongly, what I meant is instead of 
```lua
pp.metaEnvironment._DEBUG = false
pp.metaEnvironment._GAME_VERSION = "v.0.0.1"
```
is it not possible to pass `_DEBUG` and `_GAME_VERSION` directly when using the `preprocess-cmd.lua`?

**Comment by ReFreezed** [comment]
Ah, I see. You cannot pass the values directly on the command line, but you can use the `--handler=myHandler.lua` option to make LuaPreprocess execute *myHandler.lua* before processing the input files. Any globals added by *myHandler.lua* will also be globals in the processed files:

```lua
-- myHandler.lua
_G._DEBUG = false
_G._GAME_VERSION = "v.0.0.1"
return {} -- Dummy value. LuaPreprocess expects something to be returned. Example: github.com/ReFreezed/LuaPreprocess/blob/master/misc/testHandler.lua
```

**Comment by ReFreezed** [comment]
Also, about the indentation, it has to do with how the library handles whitespace around lines with `!`. I thought it was such a minor issue so I didn't fix it yet.

**Comment by ReFreezed** [comment]
I added a `--data=foo` option for the command line program. 659d6d0

**Comment by flamendless** [comment]
@ReFreezed okay got it. Please reference this issue if you commit a fix for it. 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flamendless** [comment]
@ReFreezed so single string value only? Hmmm i cant think of any usage for that right now

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flamendless** [comment]
@ReFreezed oh. This is useful. Right now my build.lua is working as referenced to yours, you may check it here and it would be awesome if you have any comment

https://github.com/flamendless/Concordia

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
