### ISSUE TITLE
Help with outputting modified string value

### ISSUE THREAD

**Issue by flamendless** [ReFreezed/LuaPreprocess#10]
I have a handler.lua with:
```lua
_C_HSPEED = toLua("hspeed")
```
Which i use like `local component = $_C_HSPEED`.

However, I also need to have something with `!` prefix like : `local n = "!hspeed"`

Ive tried:
```lua
--handler.lua
function n(component) return "!" .. component end
```
with `@@n($_C_HSPEED)` but it complains about the `!` token as it outputs `!"hspeed"` literally.

And yes, `"!" .. $_C_HSPEED` works as it generates `"!" .. "hspeed"` in the output file but this would be the last resort if no other way is possible

**Comment by ReFreezed** [comment]
Remember that macros receive code strings, so `component == "\"hspeed\""` in the `n()` function. A solution here is to [evaluate](http://luapreprocess.refreezed.com/docs/api/#evaluate) the argument, modify the value, and turn the value to code again:

```lua
function n(component)
	return toLua("!" .. evaluate(component))
end
```

**Comment by flamendless** [comment]
Thank you! Good to know and learn about evaluate
