### ISSUE TITLE
Issue with requiring files with .lua2p extension

### ISSUE THREAD

**Issue by flamendless** [ReFreezed/LuaPreprocess#2]
Hi, still tinkering with this awesome lib when I've found out that
```lua
--src/main.lua2p
local test_module
!if _DEBUG then
test_module = require("src.test_module") --"src/test_module" does not work either
!end

--src/test_modules.lua2p
local test_module = {}
!if _DEBUG then
print(1)
!else
print(2)
!end
return test_module = {}
```

error is that `src/test_module` could not be found.

Does this mean that I have change all required modules that use `src/**` to use `srcgen/**` ?

**Comment by ReFreezed** [comment]
Yes, you want to require the processed files rather than the unprocessed files...

**Comment by flamendless** [comment]
There is another solution though, and i think it would be of better sense for most users, also to keep the code base more organized.

Instead of using appending "gen" to folder names, all output should go to `bin` directory. This is easier with combination of Makefile or without by just `love bin`

**Comment by ReFreezed** [comment]
"srcgen" just happen to be what I named the output folder for my processed files because I wanted the folder to be next to the "src" folder in my file manager. How you organize the files in your project is outside the scope of the library. You just give the library an input path to read from and an output path to write to, and that's all. Just like vanilla Lua and the underlying C, the library doesn't know about the concept of directories even.

I'm not sure what your point is.

**Comment by flamendless** [comment]
Yeah, it's not specific to your library, I'm just saying the method I've found, might be useful for others who will stumble upon this.

**Comment by ReFreezed** [comment]
That's fair. Though I would think a "bin" folder would be reserved for actual binaries, like .exe and .dll/.so files etc. and not for outputted Lua text files. Wouldn't it make more sense to just call the output folder "output"? :)

**Comment by flamendless** [comment]
Yeah I've thought of output as well, but I went with bin, exe and other stuff are in "distribution".

I'll reconsider my folder naming.

**Comment by flamendless** [comment]
Hmm instead of anothet issue, I'll ask here (or do you prefer an issue for this? Just tell me) 

I assume this would work because data in handlers are "global":
```lua
--in build.lua
pp.metaEnvironment._VERSION = {0, 1, 1}

--in main.lua
print(unpack(_VERSION) ) 
```

I know that this works though
```lua
!print(unpack(_VERSION)) 
```

But for my usage (with [semver.lua](https://github.com/kikito/semver.lua) library) the first would be fitting. 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ReFreezed** [comment]
The values are "global" in the sense that they are available in the metaprogram(s). If you want values to be available in the final generated program then you have to output them in some way. Example:

```lua
-- build.lua
pp.metaEnvironment._VERSION = {0, 1, 1}

-- main.lua2p
_VERSION = !(_VERSION)
print(unpack(_VERSION))

-- Generated main.lua
_VERSION = {0,1,1}
print(unpack(_VERSION))
```

There's no way for the library to know where in the final program you want to have globals etc. defined, thus you have to explicitly output the values from your metaprogram. You could do something like this if you got many things to export:

```lua
-- build.lua
pp.metaEnvironment.values = {
	_VERSION = {0, 1, 1},
	GAME_TITLE = "Pong",
	LEVEL_FILE_EXTENSION = "level_data",
}

-- main.lua2p
!for k, v in pairs(values) do
!!(k) = !(v)
!end
-- Alternatively:
!(
for k, v in pairs(values) do
	outputLua(k, " = ")
	outputValue(v)
	outputLua("\n")
end
)

-- Generated main.lua
_VERSION = {0,1,1}
GAME_TITLE = "Pong"
LEVEL_FILE_EXTENSION = "level_data"
```

(I'm not sure what's the best way of handling miscellaneous discussions and questions on GitHub. Maybe there should be a "discussion" label for issues? Maybe I should set up a separate forum or chatroom somewhere.)

**Comment by flamendless** [comment]
Oh. I didn't know putting ! mid line is possible, thr first snippet works. Great!

Yeah, maybe discord server or just twitter dm? Up to you. I am going to use this lib thoroughly for my games

**Comment by ReFreezed** [comment]
I added a [wiki](https://github.com/ReFreezed/LuaPreprocess/wiki), which may possibly clarify some things.
