### ISSUE TITLE
Pass output path for cli

### ISSUE THREAD

**Issue by flamendless** [ReFreezed/LuaPreprocess#3]
does this already have something like this? Ive checked the wiki and havent found anything for it.

`lua preprocess-cl.lua --handler=myHandler.lua src/main.lua2p ../output/src/`

**Comment by ReFreezed** [comment]
Not yet, but I think it's a good idea.

**Comment by ReFreezed** [comment]
It's now possible to specify an output path for every input path using the `--outputpaths` flag:
```batch
lua preprocess-cl.lua --outputpaths [options] inputpath1 outputpath1 [inputpath2 outputpath2 ...]
```
Commit: d5ad045

**Comment by flamendless** [comment]
Thanks! Waiting for the wiki to specify what options are available for outputpaths

**Comment by ReFreezed** [comment]
It has the same options, or rather, `--outputpaths` is simply another option in addition to the existing ones.

**Comment by flamendless** [comment]
Does outputpaths allow the output filename like
```
lua preprocess-cli.lua - -outputpaths src/main.lua2p output/src/mymain.lua
```
Or just the `output/src`?

**Comment by ReFreezed** [comment]
You specify the full path to the file - not just the directory.
```batch
lua preprocess-cl.lua --outputpaths src/main.lua2p output/src/mymain.lua src/conf.lua2p output/src/myconf.lua
```
