### ISSUE TITLE
Malformed string

### ISSUE THREAD

**Issue by flamendless** [ReFreezed/LuaPreprocess#4]
Hi, parsing something this results to `malformed string` error

```lua
local error_msg = format("Data integrity is not valid.\n
				Please do not modify the files: '%s' and '%s'.\n
				Please delete the files in '%s' and restart the game",
				save_filename, key_filename, love.filesystem.getSaveDirectory())
```

Here's the output:
```
==============================================
= LuaPreprocess v1.11.0, 2020-08-09 12:08:54 =
==============================================
Processing 'test.lua2p'...
Error @ test.lua2p:1: [Tokenizer] Malformed string.
>
> local error_msg = format("Data integrity is not valid.\n
>--------------------------^
>
```
Making the string one-liner doesn't result to the error.

**Comment by flamendless** [comment]
Initially I thought that the issue is because of the string literals. But upon inspection, the issue is caused by multiline strings.

**Comment by ReFreezed** [comment]
The parser is actually behaving the same as the PUC Lua interpreter and LuaJIT: newlines in quoted strings must be preceded by a backslash. So if you end the lines in the example with \ instead of \n it will work (with the newlines intact).

**Comment by flamendless** [comment]
I see. I wasnt aware that lua strings should be escaped like that to support multilines. 

Thank you
