### ISSUE TITLE
Error catching for build scripts;

### ISSUE THREAD

**Issue by flamendless** [ReFreezed/LuaPreprocess#5]
Hi, I am wondering if the lib already allows returning error code when a file can't be parsed (instead of just showing an error message)

My use case is that for my bash script, I want to catch that error and not continue running my build script if an error occurred.

**Comment by flamendless** [comment]
Ive found a trick for it
```bash
echo "error('')" | lua preprocess-cl.lua test.lua2p; if [ $? -ne 0 ]; then echo "bad"; fi 
```
if script errors out, it prints `bad`

**Comment by ReFreezed** [comment]
*preprocess-cl.lua* exits with the code 0 if everything went well, or 1 if there was any error during the processing (parsing, running the metaprogram, etc.). I'm not sure how useful it would be for an outside program to know what exact error there was.

Also, my Bash knowledge is a bit limited, but I feel like the echo command and the piping is unnecessary in your solution.

**Comment by flamendless** [comment]
I see. I agree that it's doing more things that it should at the very least required. I'll look into more bash stuff.

**Comment by flamendless** [comment]
Okay so this is most minimized usage that is working:
```bash
lua preprocess-cl.lua --silent ....;
if [ $? -ne 0 ]; then
  exit;
fi
```

Might be good to include in the wiki?

**Comment by ReFreezed** [comment]
That looks more like what I would expect. :)  The Windows equivalent is:
```batch
lua preprocess-cl.lua ....
if %errorlevel% neq 0 (
    exit
)
```
Or as a short one-liner (I believe this is the same in Bash):
```batch
lua preprocess-cl.lua .... || exit
```
If the script is invoked from another Lua script it'd be:
```lua
if os.execute("lua preprocess-cl.lua ....") ~= 0 then
    os.exit()
end
```
Anyway, because all this is dependent on the environment/shell/OS I don't think it belongs in the wiki. The wiki does already say what codes the program returns which I feel is enough.

**Comment by flamendless** [comment]
Maybe for another category in wiki, like FAQ or useful tips/trick?

**Comment by ReFreezed** [comment]
I would count it as common knowledge.
