### ISSUE TITLE
require inside handler file not working

### ISSUE THREAD

**Issue by flamendless** [ReFreezed/LuaPreprocess#6]
Hi, im doing some separation for my different builds. I have `handler_dev.lua` and `handler_test.lua` that I use depending on what I want to build.

Content of `handler_dev.lua`:
```lua
_RELEASE = false
_REPORTING = false
_NETWORK = false
_ASSERT = true
_LOG_SAVE = false

require("handler")
return {}
```

Content of `handler_test.lua`:
```lua
_RELEASE = true
_REPORTING = false
_NETWORK = false
_ASSERT = false
_LOG_SAVE = false

require("handler")
return {}
```

Now, `handler.lua` is a file that contains all other metadata I need that is common to both of them, like:
```lua
_PLATFORM = "desktop"
_GAME_TITLE  = "project name"
_GAME_SIZE = { x = 1024, y = 640 }
_GAME_BASE_SIZE = { x = 128, y = 32 }

_IDENTITY = "projectname"
_LOVE_VERSION = "11.3"
_GAME_VERSION = { 0, 0, 1 }
```

But having the `require` gives this error:
`Error @ output//error_handler.lua:139: 'end' expected (to close 'if' at line 134) near 'if'`

**Comment by ReFreezed** [comment]
The library doesn't change how require() works. What files it can load depends on package.path and the current working directory, like normal. That syntax error is in your code (which I'm guessing is the outputted file, judging by the path - in which case, check that your metaprogram isn't generating invalid Lua or something as the library tries to validate outputted files which I'm guessing is what printed that error).

**Comment by flamendless** [comment]
Oh i see. So the handler files path is relatively to the lua files im preprocessing. 

--

This is a separate inquiry, but how about passing command line arguments to the handler files? Like

```
lua preprocess.lua --handler=handler.lua test foo --other args
```

Then in handler.lua be able to get the `foo` and `test`

**Comment by ReFreezed** [comment]
Well, it's specifically relative to the [working directory](https://en.wikipedia.org/wiki/Working_directory) in the running process. There's no special handling of file paths in neither the library nor Lua.

You can use the [--data](https://github.com/ReFreezed/LuaPreprocess/wiki/Command-Line#--data) option on the command line to send data to the handler (which is then available through the global `dataFromCommandLine`).

```batch
lua preprocess.lua --handler=handler.lua --data="test foo"
```

**Comment by flamendless** [comment]
Oh i missed that `--data` flag. Thank you!
