### ISSUE TITLE
[REQUEST] Allow single line conditional

### ISSUE THREAD

**Issue by flamendless** [ReFreezed/LuaPreprocess#8]
```lua
--from
!if _TEST then
    print("test")
!end

--to
!if _TEST then print("test') !end
--or perhaps a different synax.
```

**Comment by ReFreezed** [comment]
You can do this:
```lua
!(if _TEST then)  print("test")  !(end)
```
It maybe doesn't look super clean, but it works. I'm a bit hesitant to add new features as I want the library to be very simple, and I don't think adding new syntax for simpler "single line conditionals" is useful enough for the overall complexity it adds. But maybe I'll change my mind at some point.

Anyway, I often do something like this in my programs:
```lua
!(
local function ifTEST(code)
    if _TEST then  outputLua(code)  end
end
)
!ifTEST "print('test')"
```

The following is just a small hack, but if you want syntax highlighting in your text editor for the Lua code in the string you can enable params.backtickStrings when calling [processFile](https://github.com/ReFreezed/LuaPreprocess/wiki/API#processfile) (not available in the command-line interface yet) and do this:

```lua
!ifTEST `print("test")` -- Your text editor probably don't know what ` means and will just treat it as normal text, even though it's denoting a string.
```
